// Runtime Observation · judge latency card: Kev (local) against gpt-4o-mini (OpenAI API), measured on the same items.
// Everything shown comes from data/judge-latency.json, generated by jev eval/run/latency-json.ts from committed prediction files.
// The replay plays back the measured round trips in real time, one call after another per judge; nothing in it is simulated.
import { tip } from './rt-tip.js';

const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const ms = x => (x == null ? '—' : x >= 1000 ? `${(x / 1000).toFixed(2)} s` : `${Math.round(x)} ms`);
const pct = x => `${100 * x < 1 && x > 0 ? (100 * x).toFixed(1) : Math.round(100 * x)} %`;
const NAMES = { 'kev-0.8b-ft': ['Kev-0.8B, fine-tuned', 'local judge, Apple M4 Pro'], 'kev-0.8b': ['Kev-0.8B', 'local judge, Apple M4 Pro'], 'gpt-4o-mini': ['gpt-4o-mini', 'OpenAI API, over the internet'] };
const name = j => NAMES[j.label]?.[0] ?? j.label;
const short = j => (j.label.startsWith('kev') ? 'Kev' : name(j));
const REPLAY_MS = 10_000;

// Calls a judge completes within `t` ms when it answers the measured series back to back.
function doneBy(series, t) { let s = 0, n = 0; for (const x of series) { if (s + x > t) break; s += x; n++; } return n; }

let replay = 0;
function play(judges) {
  const id = ++replay, t0 = performance.now();
  const lanes = judges.map(j => ({ j, el: document.querySelector(`[data-lat-lane="${j.label}"]`) }));
  const btn = $('rtLatReplay');
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  btn.disabled = true;
  for (const { el } of lanes) el.querySelector('.rt-lat-dots').innerHTML = '';
  const frame = () => {
    if (id !== replay) return;
    const t = reduced ? REPLAY_MS : Math.min(REPLAY_MS, performance.now() - t0);
    for (const { j, el } of lanes) {
      const n = doneBy(j.rtt_series_ms, t);
      el.querySelector('[data-lat-count]').textContent = String(n);
      const dots = el.querySelector('.rt-lat-dots');
      while (dots.childElementCount < n) dots.appendChild(document.createElement('i'));
    }
    $('rtLatClock').textContent = `${(t / 1000).toFixed(1)} s`;
    if (t < REPLAY_MS) requestAnimationFrame(frame); else btn.disabled = false;
  };
  requestAnimationFrame(frame);
}

async function init() {
  const root = $('rtLatencyBody');
  if (!root) return;
  try {
    const r = await fetch('data/judge-latency.json');
    if (!r.ok) throw new Error('unavailable');
    const d = await r.json();
    const kev = d.judges.find(j => j.label === 'kev-0.8b-ft') ?? d.judges.find(j => j.label.startsWith('kev'));
    const llm = d.judges.find(j => j.label === 'gpt-4o-mini');
    const both = [kev, llm], budget = kev.within_budget.budget_ms;
    const max = Math.max(budget, ...both.map(j => j.rtt_ms.p95));
    const ratio = Math.max(llm.rtt_ms.p50, kev.rtt_ms.p50) / Math.min(llm.rtt_ms.p50, kev.rtt_ms.p50);
    const faster = kev.rtt_ms.p50 <= llm.rtt_ms.p50 ? short(kev) : short(llm);
    const v = llm.vendor_processing_ms;
    const tile = (j, note = '') => `<div class="card metric" data-lat-judge="${esc(j.label)}"><div class="kicker">${esc(name(j))} · typical answer (p50)${note}</div>
      <div class="metric-value" data-lat-p50>${ms(j.rtt_ms.p50)}</div><div class="rt-plain">Slow cases (p95): <span data-lat-p95>${ms(j.rtt_ms.p95)}</span> · ${esc(NAMES[j.label]?.[1] ?? '')}</div></div>`;
    const bar = (j, q) => `<div class="rt-lat-row"><span class="rt-lat-name">${esc(name(j))} · ${q}</span>
      <span class="rt-lat-track"><i class="${j.label.startsWith('kev') ? 'kev' : 'llm'}" style="width:${(100 * j.rtt_ms[q] / max).toFixed(1)}%"></i><b class="rt-lat-mark" style="left:${(100 * budget / max).toFixed(2)}%"></b></span><span class="rt-lat-v">${ms(j.rtt_ms[q])}</span></div>`;
    const lane = j => `<div class="rt-lat-lane" data-lat-lane="${esc(j.label)}"><div class="rt-lat-lane-head"><b>${esc(name(j))}</b><span><b data-lat-count>0</b> decisions</span></div>
      <div class="rt-lat-dots ${j.label.startsWith('kev') ? 'kev' : 'llm'}"></div></div>`;
    const bx = (100 * budget / max).toFixed(2);
    document.querySelectorAll('[data-lat-budget-intro]').forEach(e => { e.textContent = String(budget); });
    const method = `Measured on ${esc(d.host)}, ${esc(String(kev.started_at).slice(0, 10))} (UTC): the same ${kev.items} held-out benchmark items and the same judgment questions for both, one call per item, two at a time. Time is the judge's HTTP round trip, from sending the request to reading the whole answer. Failed calls: ${esc(name(kev))} ${kev.failed}, ${esc(name(llm))} ${llm.failed}.
      <span class="rt-tip-src">Kev runs locally on that machine (${esc(kev.runtime ?? 'local')}); ${esc(name(llm))} (${esc(llm.model_served ?? '')}) is called over the public internet, so its time includes the network. gpt-4o-mini is OpenAI's smaller, faster model; gpt-4o was not measured.</span>`;
    const network = tip(`Called over the public internet, so its time includes the network.${v ? ` OpenAI's own reported processing time alone was p50 ${ms(v.p50)}, p95 ${ms(v.p95)}.` : ''}`);
    root.innerHTML = `<div class="rt-learning-tiles">${tile(kev)}${tile(llm, network)}
        <div class="card metric"><div class="kicker">Answers inside the ${budget} ms gate budget</div><div class="metric-value" data-lat-within>${pct(kev.within_budget.share)} <span class="rt-lat-vs">vs</span> ${pct(llm.within_budget.share)}</div>
        <div class="rt-plain">${esc(short(kev))} vs ${esc(short(llm))} · ${esc(faster)} is ${ratio.toFixed(1)}× faster for a typical answer</div></div></div>
      <div class="rt-lat-bars card" aria-label="Round trip, p50 and p95, with the ${budget} ms gate budget">
        ${both.flatMap(j => [bar(j, 'p50'), bar(j, 'p95')]).join('')}
        <div class="rt-lat-row"><span></span><span class="rt-lat-axis"><em style="left:${bx}%">↑ ${budget} ms gate budget</em></span><span></span></div></div>
      <div class="rt-lat-race">
        <div class="rt-lat-race-head"><div><h3>Realtime: agent actions decided in 10 seconds</h3><p class="rt-ref">Plays back the measured round trips at real speed, one call after another per judge. Each dot is one decided agent action.</p></div>
          <div class="rt-lat-race-ctl"><span class="rt-lat-clock" id="rtLatClock">0.0 s</span><button type="button" class="btn" id="rtLatReplay">Replay 10 s of decisions</button></div></div>
        ${both.map(lane).join('')}
      </div>
      <p class="rt-takeaway"><b>What this means.</b> ${esc(short(kev))} answers inside the budget ${pct(kev.within_budget.share)} of the time, ${esc(name(llm))} ${pct(llm.within_budget.share)}: a small local judge can sit in the path of every agent action without making the agent wait. One location and one day, not a vendor SLA. This compares speed only, not answer quality.</p>
      <p class="rt-ref rt-tipline">How this was measured ${tip(method)}</p>`;
    $('rtLatReplay').addEventListener('click', () => play(both));
  } catch {
    root.innerHTML = '<p class="rt-ref">The latency measurements could not be loaded.</p>';
  }
}
init();
