import { esc, fmtPct, fmtMs } from '../ui/util.js';
const num = v => v == null ? '—' : Number(v).toFixed(3);
export function evidenceHtml(data) {
  const rows = Object.entries(data.models).map(([id, m]) => `<tr data-evidence-model="${esc(id)}"><th scope="row">${esc(m.label)}</th>
    <td data-evidence="io">${num(m.instruction_override.auroc)}</td><td>${num(m.goal_deviation.auroc)}</td>
    <td>${num(m.goal_deviation.threshold)}</td><td data-evidence="recall">${fmtPct(m.goal_deviation.recall)} [${m.goal_deviation.recall_ci.map(fmtPct).join(', ')}]</td>
    <td>${fmtPct(m.goal_deviation.fpr)}</td><td data-evidence="p50">${fmtMs(m.latency.p50_ms)}<small>HTTP · n=${esc(m.latency.n)}</small></td></tr>`).join('');
  const base = data.models['kev-0.8b'], ft = data.models['kev-0.8b-ft'];
  return `<h2>Measured benchmark evidence <span class="chip by">measured · benchmark labels</span></h2>
    <p>Separate from the toy model above: supervised LoRA fine-tuning on open-benchmark and heuristic-derived labels, not customer or human-reviewed labels. This is not reinforcement learning.</p>
    <p><b>${esc(data.test.benchmark)}</b> held-out test · ${esc(data.test.items)} items. goal_deviation question-level recall at each model's own calibrated threshold: ${num(base.goal_deviation.threshold)} → ${num(ft.goal_deviation.threshold)}. These are not observed agent attacks prevented.</p>
    <div class="tbl-wrap"><table class="tbl learn-evidence-table"><thead><tr><th>Model</th><th>instruction_override AUROC</th><th>goal_deviation AUROC</th><th>Threshold</th><th>Recall [95% CI]</th><th>FPR</th><th>Local p50</th></tr></thead><tbody>${rows}</tbody></table></div>
    <p>Similar local judge HTTP p50 in this run: ${fmtMs(base.latency.p50_ms)} → ${fmtMs(ft.latency.p50_ms)}; n=${esc(ft.latency.n)}. Hardware: ${esc(typeof data.hardware === 'string' ? data.hardware : JSON.stringify(data.hardware))}. No production latency guarantee.</p>
    <h3>Would this gate promote it?</h3><div class="learn-evidence-gates">${Object.entries(data.gate ?? {}).map(([id, g]) => `<article data-evidence-gate="${esc(id)}"><b>${esc(data.models[id]?.label ?? id)}: <span data-evidence-verdict>${esc(g.verdict)}</span></b><p>Fixed ${esc(g.fixed)} · Broke ${esc(g.broke)} · ${g.safetyOk ? g.evidenceOk ? 'evidence check passed' : 'needs more evidence' : g.missed.after > g.missed.before ? `Safety check failed: more missed cases (${esc(g.missed.before)} → ${esc(g.missed.after)})` : `Safety check failed: more false alarms (${esc(g.falseHolds.before)} → ${esc(g.falseHolds.after)})`}.</p><p>Missed goal-deviation cases ${esc(g.missed.before)} → ${esc(g.missed.after)} · False alarms ${esc(g.falseHolds.before)} → ${esc(g.falseHolds.after)}.</p><details data-evidence-test><summary>Paired test details</summary><p>One-sided paired test p = ${esc(g.p)} · α = ${esc(g.alpha)}. ${esc(g.items)} paired items, compared with ${esc(data.models[g.vs]?.label ?? g.vs)}.</p></details></article>`).join('')}</div><p>Question-level errors at each model’s own threshold, on one benchmark split; a retrospective check, not gateway outcomes. Production promotion is not implemented.</p>
    <details><summary>Provenance, training reference and limits</summary>
      <p>instruction_override has no fitted threshold. Calibrations are recorded, not activated. No real fine-tune on human labels has been run.</p>
      ${Object.entries(data.finetune).map(([id, f]) => `<p>${esc(id)}: ${esc(f.method)} · ${esc(f.epochs)} epochs · lr ${esc(f.lr)} · ${esc(f.records_used)} of ${esc(f.records_total)} records used · ${Math.round(f.wall_s / 60)} minutes measured. This is not the duration of the demo batch.</p>`).join('')}
      <ul>${data.caveats.map(c => `<li>${esc(c)}</li>`).join('')}</ul>
      <p>Label provenance: ${esc(JSON.stringify(data.label_provenance))}. Positive counts: ${esc(JSON.stringify(data.test.positives))}.</p>
      <p>Generated by <code>${esc(data.generated_by)}</code>. Source paths (repository files, not web links): <code>${esc(JSON.stringify(data.sources))}</code>.</p>
      <a href="data/learning-evidence.json" target="_blank" rel="noopener">View generated evidence JSON</a>
    </details>`;
}
export async function loadEvidence(root) {
  try {
    const response = await fetch(new URL('../../data/learning-evidence.json', import.meta.url));
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json(); root.innerHTML = evidenceHtml(data); root.dataset.loaded = 'true'; return data;
  } catch (error) { root.textContent = `Measured evidence unavailable (${error.message}). No substitute numbers are shown.`; root.dataset.loaded = 'error'; return null; }
}
